# This container is used for deploying AutoRAG-generated agents for inference.
# Placeholder image for initial onboarding to ODH & RHOAI (odh-autorag-inference).

ARG BASE_IMAGE="quay.io/aipcc/base-images/cpu@sha256:c82f534ada384930cdfc64bee4721a4553c7f6a3e35eee47e2399d5095e4b698"

FROM ${BASE_IMAGE}

COPY pipelines/training/autorag/documents_rag_optimization_pipeline/inference/requirements.txt \
     /tmp/

## TODO: Ensure build isolation
RUN pip install --index-url https://console.redhat.com/api/pypi/public-rhai/rhoai/3.5/cpu-ubi9/simple/ --no-cache-dir -r /tmp/requirements.txt


LABEL com.redhat.component="odh-autorag-inference-container" \
      name="managed-open-data-hub/odh-autorag-inference-rhel9" \
      description="odh-autorag-inference" \
      summary="odh-autorag-inference" \
      maintainer="['managed-open-data-hub@redhat.com']" \
      io.openshift.expose-services="" \
      io.k8s.display-name="odh-autorag-inference" \
      io.k8s.description="odh-autorag-inference" \
      com.redhat.license_terms="https://www.redhat.com/licenses/Red_Hat_Standard_EULA_20191108.pdf"
