FROM registry.redhat.io/ubi9/python-312@sha256:94300f37f9783e18b2fc3931683b89954e90b9f31124d99fa237577977798b84

WORKDIR /app

USER root

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY pyproject.toml __init__.py ./
COPY components/ components/
COPY pipelines/ pipelines/
COPY scripts/ scripts/
COPY utils/ utils/

RUN chown -R 1001:1001 /app
USER 1001

RUN pip install --no-cache-dir --no-deps .

RUN python -m scripts.generate_managed_pipelines.generate_managed_pipelines

CMD ["python", "-m", "scripts.init_managed_pipelines.init_managed_pipelines"]
