FROM registry.redhat.io/ubi9/python-312@sha256:7c894bf0e8449c8db4228cf99e4cd200c78ad9e56090055bf6073af055805cd6

WORKDIR /app

USER root

ENV PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY pyproject.toml __init__.py ./
COPY components/ components/
COPY pipelines/ pipelines/
COPY scripts/ scripts/
COPY utils/ utils/

RUN chown -R 1001:1001 /app
USER 1001

RUN pip install --no-cache-dir --no-deps .

RUN python -m scripts.generate_managed_pipelines.generate_managed_pipelines

CMD ["python", "-m", "scripts.init_managed_pipelines.init_managed_pipelines"]
