name: 'Detect Changed Components and Pipelines'
description: 'Detects changed components and pipelines in the repository'
author: 'Kubeflow Pipelines Components Team'

inputs:
  base-ref:
    description: 'Base Git reference to compare against (e.g., main, origin/main)'
    required: false
    default: ${{ format('origin/{0}', github.event.pull_request.base.ref || github.event.repository.default_branch) }}
  head-ref:
    description: 'Head Git reference to compare (defaults to current HEAD)'
    required: false
    default: 'HEAD'
  filter:
    description: 'Optional grep pattern to filter changed files (e.g., "\.py$" for Python files only)'
    required: false
    default: ''
  skip-deleted-files:
    description: 'Whether to skip deleted files (true/false)'
    required: false
    default: 'false'

outputs:
  changed-components:
    description: 'Space-separated list of changed component paths (e.g., components/training/my_trainer)'
    value: ${{ steps.detect.outputs.changed-components }}
  changed-pipelines:
    description: 'Space-separated list of changed pipeline paths (e.g., pipelines/training/my_pipeline)'
    value: ${{ steps.detect.outputs.changed-pipelines }}
  changed-components-json:
    description: 'JSON array of changed component paths'
    value: ${{ steps.detect.outputs.changed-components-json }}
  changed-pipelines-json:
    description: 'JSON array of changed pipeline paths'
    value: ${{ steps.detect.outputs.changed-pipelines-json }}
  changed-components-count:
    description: 'Number of changed components'
    value: ${{ steps.detect.outputs.changed-components-count }}
  changed-pipelines-count:
    description: 'Number of changed pipelines'
    value: ${{ steps.detect.outputs.changed-pipelines-count }}
  has-changes:
    description: 'Whether any components or pipelines have changed (true/false)'
    value: ${{ steps.detect.outputs.has-changes }}
  has-changed-components:
    description: 'Whether any components have changed (true/false)'
    value: ${{ steps.detect.outputs.has-changed-components }}
  has-changed-pipelines:
    description: 'Whether any pipelines have changed (true/false)'
    value: ${{ steps.detect.outputs.has-changed-pipelines }}
  all-changed-files:
    description: 'All changed files'
    value: ${{ steps.detect.outputs.all-changed-files }}
  filtered-changed-files:
    description: 'Changed files matching any filter pattern'
    value: ${{ steps.detect.outputs.filtered-changed-files }}

runs:
  using: 'composite'
  steps:
    - name: Detect changed assets
      id: detect
      shell: bash
      working-directory: ${{ github.workspace }}
      run: |
        python3 .github/scripts/detect_changed_assets/detect.py \
          --base-ref "${{ inputs.base-ref }}" \
          --head-ref "${{ inputs.head-ref }}" \
          --filter "${{ inputs.filter }}" \
          ${{ inputs.skip-deleted-files == 'true' && '--skip-deleted-files' || '' }}

branding:
  icon: 'file-text'
  color: 'blue'
