---
name: 'Setup Python CI'
description: 'Sets up Python and uv package manager with dependencies'

inputs:
  python-version:
    description: 'Python version to use'
    required: true
  extra:
    description: 'uv extra group to install (defaults to test)'
    required: false
    default: test

runs:
  using: 'composite'
  steps:
    - name: Set up Python ${{ inputs.python-version }}
      uses: actions/setup-python@v6
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install uv
      uses: astral-sh/setup-uv@v7

    - name: Display versions
      shell: bash
      run: |
        uv --version
        echo "Python version: $(python --version)"

    - name: Install dependencies from lock file
      shell: bash
      run: uv sync --extra ${{ inputs.extra }}
