---
modules:
  - pytest
  - kfp
  - kfp_components
files:
  # Allow any file in test directories to import from tests module
  # Glob patterns: * matches any directory, ** matches any path
  "components/**/tests/*":
    - tests
  "pipelines/**/tests/*":
    - tests
  # Allow pipelines to import the repo package at module scope
  "pipelines/*.py":
    - kfp_components
  "pipelines/**/*.py":
    - kfp_components
